insert into STATUS_PRODUCTO (STATUS_PRODUCTO_ID, CLAVE, DESCRIPCION, ACTIVO) values (1, 'ENS', 'EN SUBASTA', 1);
insert into STATUS_PRODUCTO (STATUS_PRODUCTO_ID, CLAVE, DESCRIPCION, ACTIVO) values (2, 'ENO', 'EN OFERTA', 0);
insert into STATUS_PRODUCTO (STATUS_PRODUCTO_ID, CLAVE, DESCRIPCION, ACTIVO) values (3, 'EOC', 'EN ORDEN DE COMPRA', 1);
insert into STATUS_PRODUCTO (STATUS_PRODUCTO_ID, CLAVE, DESCRIPCION, ACTIVO) values (4, 'REG', 'REGISTRADOS', 0);
insert into STATUS_PRODUCTO (STATUS_PRODUCTO_ID, CLAVE, DESCRIPCION, ACTIVO) values (5, 'ENE', 'EN ENVIO', 1);
insert into STATUS_PRODUCTO (STATUS_PRODUCTO_ID, CLAVE, DESCRIPCION, ACTIVO) values (6, 'ENT', 'ENTREGADO', 1);
insert into STATUS_PRODUCTO (STATUS_PRODUCTO_ID, CLAVE, DESCRIPCION, ACTIVO) values (7, 'CCA', 'COMPRA CANCELADA', 0);
