insert into CATEGORIA (CATEGORIA_ID, CLAVE_PRODUCTO, DESCRIPCION) values (1, 'COM', 'COMPUTO');
insert into CATEGORIA (CATEGORIA_ID, CLAVE_PRODUCTO, DESCRIPCION) values (2, 'HOG', 'HOGAR');
insert into CATEGORIA (CATEGORIA_ID, CLAVE_PRODUCTO, DESCRIPCION) values (3, 'ROP', 'ROPA');
insert into CATEGORIA (CATEGORIA_ID, CLAVE_PRODUCTO, DESCRIPCION) values (4, 'JUG', 'JUGUETES');
insert into CATEGORIA (CATEGORIA_ID, CLAVE_PRODUCTO, DESCRIPCION) values (5, 'TEL', 'TELEFONI');
insert into CATEGORIA (CATEGORIA_ID, CLAVE_PRODUCTO, DESCRIPCION) values (6, 'AUT', 'AUTOS');
insert into CATEGORIA (CATEGORIA_ID, CLAVE_PRODUCTO, DESCRIPCION) values (7, 'INM', 'INMUEBLES');