insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (1, 'Analyst Programmer', 'UDB');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (2, 'Compensation Analyst', 'JRP');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (3, 'Help Desk Operator', 'MCN');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (4, 'Clinical Specialist', 'JJJ');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (5, 'GIS Technical Architect', 'KOG');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (6, 'Developer III', 'VMA');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (7, 'Nuclear Power Engineer', 'MTZ');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (8, 'General Manager', 'IRC');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (9, 'Software Engineer II', 'LYH');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (10, 'VP Product Management', 'YDH');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (11, 'Operator', 'HPC');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (12, 'Recruiting Manager', 'YFF');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (13, 'Web Designer II', 'QYP');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (14, 'Associate Professor', 'QHA');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (15, 'Environmental Tech', 'OFN');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (16, 'Librarian', 'WYM');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (17, 'Payment Adjustment Coordinator', 'IIU');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (18, 'Occupational Therapist', 'NBJ');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (19, 'Nurse Practicioner', 'PNE');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (20, 'Financial Advisor', 'DIR');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (21, 'Automation Specialist II', 'BGX');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (22, 'Quality Engineer', 'BPH');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (23, 'Senior Cost Accountant', 'MYL');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (24, 'Chemical Engineer', 'NFJ');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (25, 'Structural Engineer', 'SLM');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (26, 'Recruiter', 'BDE');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (27, 'Marketing Manager', 'JCU');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (28, 'Design Engineer', 'ZZI');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (29, 'Help Desk Operator', 'JEO');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (30, 'GIS Technical Architect', 'ZBC');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (31, 'Analog Circuit Design manager', 'SRH');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (32, 'Information Systems Manager', 'POV');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (33, 'Structural Analysis Engineer', 'BZK');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (34, 'Assistant Manager', 'KGS');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (35, 'Electrical Engineer', 'QGG');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (36, 'Professor', 'KRZ');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (37, 'Database Administrator II', 'LGQ');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (38, 'Help Desk Technician', 'QHJ');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (39, 'Software Consultant', 'IKV');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (40, 'Administrative Officer', 'BMN');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (41, 'Occupational Therapist', 'HXK');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (42, 'Staff Accountant IV', 'MFD');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (43, 'Tax Accountant', 'WYV');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (44, 'Senior Editor', 'VLZ');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (45, 'Marketing Manager', 'ODN');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (46, 'Human Resources Manager', 'LHT');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (47, 'Database Administrator II', 'SFY');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (48, 'Senior Sales Associate', 'GOX');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (49, 'Speech Pathologist', 'YQT');
insert into OCUPACION (OCUPACION_ID, DESCRIPCION, CLAVE_OCUPACION) values (50, 'Sales Associate', 'HVY');
