--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      fi.unam.bda
-- Project :      e-Market - geco.DM1
-- Author :       DELL
--
-- Date Created : Monday, June 03, 2024 14:46:09
-- Target DBMS : Oracle 11g
--
whenever sqlerror exit rollback

connect admin_usuario/usuarioA
-- 
-- TABLE: USUARIOS.USUARIO 
--
prompt Creando tabla USUARIO
CREATE TABLE USUARIO(
    USUARIO_ID        NUMBER(10,0)    NOT NULL,
    RFC               VARCHAR2(13)     NOT NULL,
    NOMBRE            VARCHAR2(15)     NOT NULL,
    APELLIDOS         VARCHAR2(50)     NOT NULL,
    USER_NAME         VARCHAR2(30)     NOT NULL,
    FOTO              BLOB,
    EMAIL             VARCHAR2(40)     NOT NULL,
    FECHA_REGISTRO    DATE             NOT NULL,
    CONTRASENIA       VARCHAR2(20)     NOT NULL,
    ES_COMPRADOR      NUMBER(1,0)     NOT NULL,
    ES_VENDEDOR       NUMBER(1,0)     NOT NULL,
    CONSTRAINT USUARIO_PK PRIMARY KEY (USUARIO_ID)
      USING INDEX (
        CREATE UNIQUE INDEX USUARIO_PK ON 
          USUARIO(USUARIO_ID) tablespace ESCO_INDEX
      )
)
tablespace ESCO_USUARIO
LOB(FOTO) STORE AS (tablespace ESCO_BINARIOS);

-- 
-- TABLE: USUARIO.OCUPACION 
--
prompt Creando tabla OCUPACION
CREATE TABLE OCUPACION(
    OCUPACION_ID       NUMBER(2, 0)    NOT NULL,
    DESCRIPCION        VARCHAR2(20)    NOT NULL,
    CLAVE_OCUPACION    VARCHAR2(5)     NOT NULL,
    CONSTRAINT OCUPACION_PK PRIMARY KEY (OCUPACION_ID)
      USING INDEX (
        CREATE UNIQUE INDEX OCUPACION_PK ON 
          OCUPACION(OCUPACION_ID) tablespace ESCO_INDEX
      )
)
tablespace ESCO_CATALOGOS;



-- 
-- TABLE: USUARIO.COMPRADOR 
--
prompt Creando tabla COMPRADOR
CREATE TABLE COMPRADOR(
    USUARIO_ID          NUMBER(10, 0)    NOT NULL,
    DESCRIPCION         VARCHAR2(200)    NOT NULL,
    TELEFONO_CELULAR    NUMBER(10, 0)    NOT NULL,
    OCUPACION_ID        NUMBER(2, 0)     NOT NULL,
    CONSTRAINT COMPRADOR_PK PRIMARY KEY (USUARIO_ID) 
      USING INDEX (
        CREATE UNIQUE INDEX COMPRADOR_PK ON 
          COMPRADOR(USUARIO_ID) tablespace ESCO_INDEX
      ),
    CONSTRAINT COMPRADOR_USUARIO_ID_FK FOREIGN KEY (USUARIO_ID)
    REFERENCES USUARIO(USUARIO_ID),
    CONSTRAINT COMPRADOR_OCUPACION_ID_FK FOREIGN KEY (OCUPACION_ID)
    REFERENCES OCUPACION(OCUPACION_ID)
)
tablespace ESCO_USUARIO;


-- 
-- TABLE: USUARIO.EMPRESA_PAQUETERIA 
--
prompt Creando tabla EMPRESA_PAQUETERIA
CREATE TABLE EMPRESA_PAQUETERIA(
    EMPRESA_ID        NUMBER(10, 0)    NOT NULL,
    NOMBRE_EMPRESA    VARCHAR2(30)     NOT NULL,
    CONSTRAINT EMPRESA_PAQUETERIA_PK PRIMARY KEY (EMPRESA_ID)
      USING INDEX (
        CREATE UNIQUE INDEX EMPRESA_PAQUETERIA_PK ON 
          EMPRESA_PAQUETERIA(EMPRESA_ID) tablespace ESCO_INDEX
      )
)
tablespace ESCO_CATALOGOS;


-- 
-- TABLE: USUARIO.TARJETA_CREDITO 
--
prompt Creando tabla TARJETA_CREDITO
CREATE TABLE TARJETA_CREDITO(
    TARJETA_ID      CHAR(10)         NOT NULL,
    NO_TARJETA      CHAR(18)         NOT NULL,
    BANCO           VARCHAR2(30)     NOT NULL,
    ANIO_EXP         CHAR(4)          NOT NULL,
    MES_EXP         CHAR(2)          NOT NULL,
    NO_SEGURIDAD    CHAR(4)          NOT NULL,
    USUARIO_ID      NUMBER(10, 0)    NOT NULL,
    CONSTRAINT TARJETA_CREDITO_PK PRIMARY KEY (TARJETA_ID)
      USING INDEX (
        CREATE UNIQUE INDEX TARJETA_CREDITO_PK ON 
          TARJETA_CREDITO(TARJETA_ID) tablespace ESCO_INDEX
      ),
    CONSTRAINT TARJETA_CREDITO_USUARIO_ID_FK FOREIGN KEY (USUARIO_ID)
    REFERENCES COMPRADOR(USUARIO_ID)
)
tablespace ESCO_TARJETAS;


-- 
-- TABLE: USUARIO.ORDEN_COMPRA 
--
prompt Creando tabla ORDEN_COMPRA
CREATE TABLE ORDEN_COMPRA(
    ORDEN_COMPRA_ID         NUMBER(10,0)    NOT NULL,
    FECHA_HORA              DATE             NOT NULL,
    METODO_PAGO             VARCHAR2(1)      NOT NULL,
    DIRECCION               VARCHAR2(200)    NOT NULL,
    TARJETA_ID              CHAR(10)         NOT NULL,
    SUBASTA_PRODUCTO_RID    NUMBER(10,2)    NOT NULL,
    CONSTRAINT ORDEN_COMPRA_PK PRIMARY KEY (ORDEN_COMPRA_ID)
      USING INDEX (
        CREATE UNIQUE INDEX ORDEN_COMPRA_PK ON 
          ORDEN_COMPRA(ORDEN_COMPRA_ID) tablespace ESCO_INDEX
      ), 
    CONSTRAINT ORDEN_COMPRA_TARJETA_ID_FK FOREIGN KEY (TARJETA_ID)
    REFERENCES TARJETA_CREDITO(TARJETA_ID),
    CONSTRAINT ORDEN_COMPRA_METODO_PAGO_CHK CHECK (
        METODO_PAGO IN ('1', '3', '6')
    )
    
)tablespace ESCO_COMPRAS;


-- 
-- TABLE: USUARIO.FACTURA 
--
prompt Creando tabla FACTURA
CREATE TABLE FACTURA(
    FOLIO                NUMBER(10, 0)    NOT NULL,
    MONTO_TOTAL          NUMBER(10, 0)    NOT NULL,
    COMISION_SERVICIO    NUMBER(10, 0)    NOT NULL,
    EMPRESA_ID           NUMBER(10, 0)    NOT NULL,
    ORDEN_COMPRA_ID      NUMBER(10, 0)    NOT NULL,
    CONSTRAINT FACTURA_PK PRIMARY KEY (FOLIO)
      USING INDEX (
        CREATE UNIQUE INDEX FACTURA_PK ON 
          FACTURA(FOLIO) tablespace ESCO_INDEX
      ), 
    CONSTRAINT FACTURA_ORDEN_COMPRA_ID_FK FOREIGN KEY (ORDEN_COMPRA_ID)
    REFERENCES ORDEN_COMPRA(ORDEN_COMPRA_ID),
    CONSTRAINT FACTURA_EMPRESA_ID_FK FOREIGN KEY (EMPRESA_ID)
    REFERENCES EMPRESA_PAQUETERIA(EMPRESA_ID)
)
tablespace ESCO_COMPRAS;


-- 
-- TABLE: USUARIO.ENCUESTA_SASTIFACCION 
--
prompt Creando tabla ENCUESTA_SASTIFACCION
CREATE TABLE ENCUESTA_SASTIFACCION(
    CALIFICACION_ID         NUMBER(10, 0)    NOT NULL,
    COMENTARIOS             VARCHAR2(200),
    PUNTUACION              NUMBER(1, 0)     NOT NULL,
    USUARIO_ID              NUMBER(10, 0)    NOT NULL,
    FOLIO                   NUMBER(10, 0)    NOT NULL,
    SUBASTA_PRODUCTO_RID    NUMBER(10, 2)    NOT NULL,
    CONSTRAINT ENCUESTA_SASTIFACCION_PK PRIMARY KEY (CALIFICACION_ID)
      USING INDEX (
        CREATE UNIQUE INDEX ENCUESTA_SASTIFACCION_PK ON 
          ENCUESTA_SASTIFACCION(CALIFICACION_ID) tablespace ESCO_INDEX
      ), 
    CONSTRAINT ENCUESTA_SASTIFACCION_PUNTUACION_CHK CHECK (
        PUNTUACION IN ('0', '1', '2','3','4','5')
    ),
    CONSTRAINT ENCUESTA_SATISFACCION_FOLIO_FK FOREIGN KEY (FOLIO)
    REFERENCES FACTURA(FOLIO),
    CONSTRAINT ENCUESTA_SASTIFACCION_USUARIO_ID_FK FOREIGN KEY (USUARIO_ID)
    REFERENCES COMPRADOR(USUARIO_ID)
)
tablespace ESCO_COMPRAS;


-- 
-- TABLE: USUARIO.UBICACION_PAQUETE 
--
prompt Creando tabla UBICACION_PAQUETE
CREATE TABLE UBICACION_PAQUETE(
    PAQUETE_ID      NUMBER(15, 0)    NOT NULL,
    FOLIO           NUMBER(10, 0)    NOT NULL,
    FECHA_STATUS    DATE     NOT NULL,
    LATITUD         BINARY_DOUBLE    NOT NULL,
    LONGITUD        BINARY_DOUBLE    NOT NULL,
    CONSTRAINT UBICACION_PAQUETE_PK PRIMARY KEY (PAQUETE_ID)
      USING INDEX (
        CREATE UNIQUE INDEX UBICACION_PAQUETE_PK ON 
          UBICACION_PAQUETE(PAQUETE_ID) tablespace ESCO_INDEX
      ), 
    CONSTRAINT UBICACION_PAQUETE_FOLIO_PK FOREIGN KEY (FOLIO)
    REFERENCES FACTURA(FOLIO)
)
tablespace ESCO_COMPRAS;


-- 
-- TABLE: USUARIO.VENDEDOR
--
prompt Creando tabla VENDEDOR
CREATE TABLE VENDEDOR(
    USUARIO_ID               NUMBER(10, 0)    NOT NULL,
    TIPO_VENDEDOR            VARCHAR2(1),
    CALIFICACION_PROMEDIO    BINARY_FLOAT     NOT NULL,
    DIRECCION                VARCHAR2(200)    NOT NULL,
    CONSTRAINT VENDEDOR_PK PRIMARY KEY (USUARIO_ID)
      USING INDEX (
        CREATE UNIQUE INDEX VENDEDOR_PK ON 
          VENDEDOR(USUARIO_ID) tablespace ESCO_INDEX
      ), 
    CONSTRAINT VENDEDOR_TIPO_VENDEDOR_CHK CHECK (
        TIPO_VENDEDOR IN ('E', 'e', 'P','p')
    ),
    CONSTRAINT VENDEDOR_USUARIO_ID_FK FOREIGN KEY (USUARIO_ID)
    REFERENCES USUARIO(USUARIO_ID)
)
tablespace ESCO_USUARIO;


-- 
-- USUARIOS
--

-- 
-- index: USUARIO_RFC_UK
--
CREATE UNIQUE INDEX USUARIO_RFC_UK ON USUARIO(RFC) tablespace ESCO_INDEX;

-- 
-- index: USUARIO_UK
--

CREATE UNIQUE INDEX USUARIO_USER_NAME_UK ON USUARIO(USER_NAME) tablespace ESCO_INDEX;

-- 
-- index: USUARIO_EMAIL_UK
--

CREATE UNIQUE INDEX USUARIO_EMAIL_UK ON USUARIO(EMAIL) tablespace ESCO_INDEX;

-- 
-- index: TARJETA_CREDITO_NO_TARJETA_UK
--

CREATE UNIQUE INDEX TARJETA_CREDITO_NO_TARJETA_UK ON TARJETA_CREDITO(NO_TARJETA) tablespace ESCO_INDEX;
