--Autor Giselle Espinosa
--Fecha de creacion 05/junio/2024
--Descripcion Creacion de las tablas correspondientes al modulo PRODUCTO

whenever sqlerror exit rollback

connect admin_product/producto
-- 
-- TABLE: PRODUCTO.CATEGORIA 
--
whenever sqlerror exit rollback

CREATE TABLE CATEGORIA(
    CATEGORIA_ID      NUMBER(10, 0)    NOT NULL,
    CLAVE_PRODUCTO    CHAR(10)         NOT NULL,
    DESCRIPCION       VARCHAR2(100)    NOT NULL,
    CONSTRAINT CATEGORIA_PK PRIMARY KEY (CATEGORIA_ID)
      USING INDEX (
        CREATE UNIQUE INDEX CATEGORIA_PK ON 
          CATEGORIA(CATEGORIA_ID) TABLESPACE ESCO_INDEX
      )
) 
TABLESPACE ESCO_CATALOGOS;


-- 
-- TABLE: PRODUCTO.STATUS_PRODUCTO 
--

CREATE TABLE STATUS_PRODUCTO(
    STATUS_PRODUCTO_ID    NUMBER(10, 0)    NOT NULL,
    CLAVE                 VARCHAR2(40)     NOT NULL,
    DESCRIPCION           VARCHAR2(50)     NOT NULL,
    ACTIVO                NUMBER(1, 0)     NOT NULL,
    CONSTRAINT STATUS_PRODUCTO_PK PRIMARY KEY (STATUS_PRODUCTO_ID)
      USING INDEX (
        CREATE UNIQUE INDEX STATUS_PRODUCTO_PK ON 
          STATUS_PRODUCTO(STATUS_PRODUCTO_ID) TABLESPACE ESCO_INDEX
      )
)
TABLESPACE ESCO_PRODUCTO;


-- 
-- TABLE: PRODUCTO.PRODUCTO 
--

CREATE TABLE PRODUCTO(
    PRODUCTO_ID           NUMBER(7, 0)     NOT NULL,
    NOMBRE_PRODUCTO       VARCHAR2(50)     NOT NULL,
    DESCRIPCION           VARCHAR2(500)    NOT NULL,
    PRECIO_INICIAL        NUMBER(10, 0)    NOT NULL,
    VIDEO                 BLOB,
    INICIO_VIDA_UTIL      DATE             NOT NULL,
    DESC_DEFECTOS         VARCHAR2(200)    NOT NULL,
    FECHA_STATUS          DATE    NOT NULL,
    CATEGORIA_ID          NUMBER(10, 0)    NOT NULL,
    STATUS_PRODUCTO_ID    NUMBER(10, 0)    NOT NULL,
    VENDEDOR_RID          NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PRODUCTO_PK PRIMARY KEY (PRODUCTO_ID)
      USING INDEX (
        CREATE UNIQUE INDEX PRODUCTO_PK ON 
          PRODUCTO(PRODUCTO_ID) TABLESPACE ESCO_INDEX
      ), 
    CONSTRAINT PRODUCTO_CATEGORIA_ID_FK FOREIGN KEY (CATEGORIA_ID)
    REFERENCES CATEGORIA(CATEGORIA_ID),
    CONSTRAINT PRODUCTO_STATUS_PRODUCTO_ID_FK FOREIGN KEY (STATUS_PRODUCTO_ID)
    REFERENCES STATUS_PRODUCTO(STATUS_PRODUCTO_ID)
)TABLESPACE ESCO_PRODUCTO
LOB(VIDEO) STORE AS (TABLESPACE ESCO_BINARIOS);



-- 
-- TABLE: PRODUCTO.FOTO_PRODUCTO 
--

CREATE TABLE FOTO_PRODUCTO(
    NUM_FOTO       NUMBER(2, 0)    NOT NULL,
    PRODUCTO_ID    NUMBER(7, 0)    NOT NULL,
    ARCHIVO        BLOB            NOT NULL,
    CONSTRAINT FOTO_PRODUCTO_PK PRIMARY KEY (NUM_FOTO, PRODUCTO_ID)
      USING INDEX (
        CREATE UNIQUE INDEX FOTO_PRODUCTO_PK ON 
          FOTO_PRODUCTO(NUM_FOTO,PRODUCTO_ID) TABLESPACE ESCO_INDEX
      ), 
    CONSTRAINT FOTO_PRODUCTO_ID_FK FOREIGN KEY (PRODUCTO_ID)
    REFERENCES PRODUCTO(PRODUCTO_ID)
)TABLESPACE ESCO_PRODUCTO
LOB(ARCHIVO) STORE AS (TABLESPACE ESCO_BINARIOS);



-- 
-- TABLE: PRODUCTO.HISTORICO_STATUS_PRODUCTO 
--

CREATE TABLE HISTORICO_STATUS_PRODUCTO(
    HISTORICO_STATUS_PRODUCTO_ID    NUMBER(10, 0)    NOT NULL,
    FECHA_STATUS                 VARCHAR2(40)     NOT NULL,
    STATUS_PRODUCTO_ID           NUMBER(10, 0)    NOT NULL,
    PRODUCTO_ID                  NUMBER(7, 0)     NOT NULL,
    CONSTRAINT HISTORICO_STATUS_PRODUCTO_PK PRIMARY KEY (HISTORICO_STATUS_PRODUCTO_ID)
      USING INDEX (
        CREATE UNIQUE INDEX HISTORICO_STATUS_PRODUCTO_PK ON 
          HISTORICO_STATUS_PRODUCTO(HISTORICO_STATUS_PRODUCTO_ID) TABLESPACE ESCO_INDEX
      ), 
    CONSTRAINT HISTORICO_STATUS_PRODUCTO_ID_FK FOREIGN KEY (STATUS_PRODUCTO_ID)
    REFERENCES STATUS_PRODUCTO(STATUS_PRODUCTO_ID),
    CONSTRAINT HISTORICO_STATUS_PRODUCTO_P_ID_FK FOREIGN KEY (PRODUCTO_ID)
    REFERENCES PRODUCTO(PRODUCTO_ID)
)TABLESPACE ESCO_PRODUCTO;


-- 
-- TABLE: PRODUCTO.OFERTA 
--

CREATE TABLE OFERTA(
    OFERTA_ID            NUMBER(10, 0)    NOT NULL,
    FECHA_HORA           DATE     NOT NULL,
    IMPORTE_A_OFRECER    NUMBER(10, 2)    NOT NULL,
    PRODUCTO_ID          NUMBER(7, 0)     NOT NULL,
    COMPRADOR_RID        NUMBER(10, 0)    NOT NULL,
    CONSTRAINT OFERTA_PK PRIMARY KEY (OFERTA_ID)
      USING INDEX (
        CREATE UNIQUE INDEX OFERTA_PK ON 
          OFERTA(OFERTA_ID) TABLESPACE ESCO_INDEX
      ), 
    CONSTRAINT OFERTA_PRODUCTO_ID_FK FOREIGN KEY (PRODUCTO_ID)
    REFERENCES PRODUCTO(PRODUCTO_ID)
)TABLESPACE ESCO_OFERTAS;


-- 
-- TABLE: PRODUCTO.SUBASTA 
--

CREATE TABLE SUBASTA(
    SUBASTA_ID           NUMBER(10, 0)    NOT NULL,
    FECHA_HORA_INICIO    DATE             NOT NULL,
    FECHA_HORA_CIERRE    DATE             NOT NULL,
    TOTAL_PRODUCTOS      CHAR(10)         NOT NULL,
    CONSTRAINT SUBASTA_PK PRIMARY KEY (SUBASTA_ID)
      USING INDEX (
        CREATE UNIQUE INDEX SUBASTA_PK ON 
          SUBASTA(SUBASTA_ID) TABLESPACE ESCO_INDEX
      )
)TABLESPACE ESCO_SUBASTA;


-- 
-- TABLE: PRODUCTO.SUBASTA_PRODUCTO 
--

CREATE TABLE SUBASTA_PRODUCTO(
    SUBASTA_PRODUCTO_ID    NUMBER(10, 2)    NOT NULL,
    PRODUCTO_ID            NUMBER(7, 0)     NOT NULL,
    SUBASTA_ID             NUMBER(10, 0)    NOT NULL,
    CONSTRAINT SUBASTA_PRODUCTO_PK PRIMARY KEY (SUBASTA_PRODUCTO_ID)
      USING INDEX (
        CREATE UNIQUE INDEX SUBASTA_PRODUCTO_PK ON 
          SUBASTA_PRODUCTO(SUBASTA_PRODUCTO_ID) TABLESPACE ESCO_INDEX
      ), 
    CONSTRAINT SUBASTA_PRODUCTO_ID_FK FOREIGN KEY (PRODUCTO_ID)
    REFERENCES PRODUCTO(PRODUCTO_ID),
    CONSTRAINT SUBASTA_PRODUCTO_SUBASTA_ID_FK FOREIGN KEY (SUBASTA_ID)
    REFERENCES SUBASTA(SUBASTA_ID)
)TABLESPACE ESCO_SUBASTA;





